name: CI
on:
  pull_request:
  push:
  schedule:
  - cron: '0 4 * * 3'
jobs:
  test:
    runs-on: ubuntu-latest
    timeout-minutes: 30
    strategy:
      fail-fast: false
      matrix:
        include:
          - java: 11
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-java@v3
      with:
        java-version: "${{ matrix.java }}"
        distribution: temurin
    - uses: coursier/cache-action@v6
    - run: sbt -v
           "+ scalafmtCheckAll"
           scalafmtSbtCheck
           "+ test"
