name: CI
on:
  pull_request:
  push:
  schedule:
  - cron: '0 4 * * 3'
jobs:
  test:
    runs-on: ubuntu-latest
    timeout-minutes: 30
    strategy:
      fail-fast: false
      matrix:
        include:
          - java: 17
          - java: 21
    steps:
    - uses: actions/checkout@v5
    - uses: actions/setup-java@v4
      with:
        java-version: "${{ matrix.java }}"
        distribution: temurin
    - uses: coursier/cache-action@v6
    - uses: sbt/setup-sbt@v1
    - run: sbt -v
           -J-Xmx5G
           "+ scalafmtCheckAll"
           scalafmtSbtCheck
           "+ test"
